### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by michakrapp** [fairpm/server#6]
From README
> Better Docker Compose setup coming soon!

Maybe integrate **DDEV** which is basically a wrapper for docker-compose for easier handling.
https://ddev.com/

It has integration for WordPress, as well as WP-CLI
https://ddev.readthedocs.io/en/stable/users/quickstart/#wordpress-wp-cli

Also DB, redis, etc. can be integrated.

If a user/dev has the prerequisites (docker, ddev), it is as simple as `ddev start`

**Comment by rmccue** [comment]
This is the Docker Compose I'm currently using (albeit with tweaked domain names):

```yaml
name: server

services:
  db:
    image: 'mysql:8.0'
    command: '--log-error-suppression-list=MY-013360 --default-authentication-plugin=mysql_native_password --skip-ssl'
    container_name: server-db
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
        - '-u'
        - wordpress
        - '-pwordpress'
      timeout: 5s
      interval: 5s
      retries: 10

  redis:
    image: 'redis:7.0-alpine'
    container_name: server-redis
    ports:
      - '6379'

  php:
    container_name: server-php
    image: docker.io/library/wordpress:6.8.1-fpm
    init: true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
    external_links:
      - 'proxy:fair.local'
    volumes:
      - '.:/var/www/html:delegated'
      - './tools/local/config/php.ini:/usr/local/etc/php/conf.d/99-custom.ini'
      - './tools/local/config/php-fpm.ini:/usr/local/etc/php-fpm.d/z-www.conf'
      - 'tmp:/tmp'
    ports:
      - '9000'
    networks:
      - proxy
      - default
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      REDIS_HOST: server-redis
      REDIS_PORT: 6379

  cli:
    container_name: server-cli
    image: docker.io/library/wordpress:cli-php8.2
    command: ["sleep", "infinity"]
    init: true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
    external_links:
      - 'proxy:fair.local'
    volumes:
      - '.:/var/www/html:delegated'
      - './tools/local/config/php.ini:/usr/local/etc/php/conf.d/99-custom.ini'
      - './tools/local/config/php-fpm.ini:/usr/local/etc/php-fpm.d/z-www.conf'
      - 'tmp:/tmp'
    networks:
      - proxy
      - default
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      REDIS_HOST: server-redis
      REDIS_PORT: 6379

  nginx:
    image: 'nginxinc/nginx-unprivileged:latest'
    container_name: server-nginx
    networks:
      - proxy
      - default
    depends_on:
      - php
    volumes:
      - '.:/app:delegated'
      - './tools/local/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './tools/local/config/fastcgi_params:/etc/nginx/fastcgi_params:ro'
    ports:
      - '8080'
    labels:
      - traefik.frontend.priority=1
      - traefik.port=8080
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=HostRegexp:fair.local,{subdomain:[A-Za-z0-9.-]+}.fair.local'
      - 'traefik.domain=fair.local,*.fair.local'
    environment:
      GZIP_STATUS: 'on'
      READ_TIMEOUT: 60s
      PHP_PUBLIC_POOL_ENABLE_RATE_LIMIT: 'false'

networks:
  default: null
  proxy:
    name: proxy
    external: true

volumes:
  db-data: null
  tmp: null

```

It requires manually mapping domain DNS, running Traefik, and setting up DNS records though, so it's not really usable out-of-the-box right now.
